version: 2
jobs:
  build-ui:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo/ui
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          working_directory: ~/repo/ui
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: npm run build


