version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo/ui
    steps:
      - checkout:
          path: ~/repo
      - run: npm install
      - run: npx lerna bootstrap
      - run: npx lerna run build
      - run: npx lerna run prepare-pkg
      - run: npx lerna run pkg
workflows:
  version: 2
  build:
    jobs:
      - build
