version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run: npx lerna bootstrap
      - run: npx lerna run build
      - run: npx lerna run prepare-pkg
      - run: npx lerna run pkg
      - run: pwd
      - run: ls -la packages/mond/bin
      - persist_to_workspace:
          root: packages/mond
          paths:
            - bin

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - checkout
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(git name-rev --tags --name-only $(git rev-parse HEAD))
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/bin/

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
